import * as React from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { setMathType } from '../../redux/MathReducer';

export interface IAppProps {
}

export default function GameSelect (props: IAppProps) {

    const dispatch = useDispatch()
    const mathData = useSelector((state:any) => state.math.value)


    // When game mode is clicked, sets type in MathReducer to either of the four types. Which will be regulate the questions generated by "GernerateMathProblems"
    function selectGameType(type:string) { dispatch(setMathType({type})) }


  return (
    <div className='gameSelect'>
      
        <div className="gameSelect_title">
            <p>Quiz Wars</p>
        </div>
      
        <div className="gameSelect_select">
            <div className="gameSelect_select_title"><p>Choose Game Type</p></div>
            <div className="gameSelect_select_buttonSection">
                <div id="choose_addition" className="gameSelect_select_buttonSection_button" onClick={() => selectGameType("addition")}><p>Addition</p><p>Biggest number</p><p>20 + 20</p></div>
                <div id="choose_substraction" className="gameSelect_select_buttonSection_button" onClick={() => selectGameType("substraction")}><p>Substraction</p><p>Biggest number</p><p>20 - 20</p></div>
                <div id="choose_multiplication" className="gameSelect_select_buttonSection_button" onClick={() => selectGameType("multiplication")}><p>Multiplication</p><p>Biggest number</p><p>10 x 10</p></div>
                <div id="choose_division" className="gameSelect_select_buttonSection_button" onClick={() => selectGameType("division")}><p>Division</p><p>Biggest number</p><p>20 + 20</p></div>
            </div>
        </div>


        <div className="gameSelect_start">
            {mathData.type === "" ? (

                    <button disabled id="notSelectedBtn" className="gameSelect_start_button"><p>Choose Game Type</p></button>

            ) : (

                <Link style={{ textDecoration: 'none' }} to="/hostlobby">
                    <button className="gameSelect_start_button"><p>Start Game</p></button>
                </Link>

            )}
        </div>

    </div>
  );
}
