import regions from "../images/RegionImageExport"

export const RegionData = [
    
    {id: 0, mapId:"mapID00", name:"Forest's Edge", img: regions[0], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "Green"},
    {id: 1, mapId:"mapID01", name:"Emeraldwood", img: regions[1], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 2, mapId:"mapID02", name:"Verdant Vale", img: regions[2], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 3, mapId:"mapID03", name:"Greenbriar", img: regions[3], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 4, mapId:"mapID04", name:"Meadowdale", img: regions[4], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 5, mapId:"mapID05", name:"Grassland Groves", img: regions[5], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 6, mapId:"mapID06", name:"Prairiebloom", img: regions[6], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 7, mapId:"mapID07", name:"Wildwood Hills", img: regions[7], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 8, mapId:"mapID08", name:"Lushwood", img: regions[8], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 9, mapId:"mapID09", name:"Verdant Plains", img: regions[9], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 10, mapId:"mapID10", name:"Greenhaven", img: regions[10], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},

    {id: 11, mapId:"mapID11", name:"Woodland's Sanctuary", img: regions[11], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 12, mapId:"mapID12", name:"Frozen Glade", img: regions[12], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 13, mapId:"mapID13", name:"Leafy Hills", img: regions[13], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 14, mapId:"mapID14", name:"Emerald Grove", img: regions[14], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 15, mapId:"mapID15", name:"Grassland's Oasis", img: regions[15], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 16, mapId:"mapID16", name:"Arborwatch", img: regions[16], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 17, mapId:"mapID17", name:"Treewind", img: regions[17], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 18, mapId:"mapID18", name:"Woodland's Crown", img: regions[18], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 19, mapId:"mapID19", name:"Forest's Heart", img: regions[19], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 20, mapId:"mapID20", name:"Snowfall Mountains", img: regions[20], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},

    {id: 21, mapId:"mapID21", name:"White Peak", img: regions[21], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 22, mapId:"mapID22", name:"Snowy Heights", img: regions[22], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 23, mapId:"mapID23", name:"Treefrost", img: regions[23], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 24, mapId:"mapID24", name:"Farmstead", img: regions[24], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 25, mapId:"mapID25", name:"Fieldstone", img: regions[25], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 26, mapId:"mapID26", name:"Cropcrest", img: regions[26], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 27, mapId:"mapID27", name:"Barrenwatch", img: regions[27], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 28, mapId:"mapID28", name:"Barren's Bluff", img: regions[28], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 29, mapId:"mapID29", name:"Boulders End", img: regions[29], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 30, mapId:"mapID30", name:"Greenvale", img: regions[30], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},

    {id: 31, mapId:"mapID31", name:"Craggy Heights", img: regions[31], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 32, mapId:"mapID32", name:"Stonehold", img: regions[32], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 33, mapId:"mapID33", name:"Darkwood", img: regions[33], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 34, mapId:"mapID34", name:"Evil's Edge", img: regions[34], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 35, mapId:"mapID35", name:"Shadow's Den", img: regions[35], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 36, mapId:"mapID36", name:"Leaf's fall", img: regions[36], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 37, mapId:"mapID37", name:"Blackmount", img: regions[37], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 38, mapId:"mapID38", name:"Wicked Woods", img: regions[38], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "Red"},
    {id: 39, mapId:"mapID39", name:"Dread Peak", img: regions[39], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 40, mapId:"mapID40", name:"Shadowed Slope", img: regions[40], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},

    {id: 41, mapId:"mapID41", name:"Muckmire", img: regions[41], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 42, mapId:"mapID42", name:"Duneswept", img: regions[42], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 43, mapId:"mapID43", name:"Bogwood", img: regions[43], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 44, mapId:"mapID44", name:"Desert's Edge", img: regions[44], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 45, mapId:"mapID45", name:"Aridlands", img: regions[45], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 46, mapId:"mapID46", name:"Canyonside", img: regions[46], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 47, mapId:"mapID47", name:"Fenland", img: regions[47], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 48, mapId:"mapID48", name:"Sloughwater", img: regions[48], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 49, mapId:"mapID49", name:"Bogland", img: regions[49], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 50, mapId:"mapID50", name:"Fen's Den", img: regions[50], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},

    {id: 51, mapId:"mapID51", name:"Crown Isle", img: regions[51], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 52, mapId:"mapID52", name:"Firewatch", img: regions[52], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 53, mapId:"mapID53", name:"Ashmount", img: regions[53], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "Yellow"},
    {id: 54, mapId:"mapID54", name:"Scorched Summit", img: regions[54], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 55, mapId:"mapID55", name:"The Great Pass", img: regions[55], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 56, mapId:"mapID56", name:"Summergate", img: regions[56], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 57, mapId:"mapID57", name:"Timberland", img: regions[57], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 58, mapId:"mapID58", name:"Rootwood", img: regions[58], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 59, mapId:"mapID59", name:"Mountain's Fury", img: regions[59], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 60, mapId:"mapID60", name:"Argonien", img: regions[60], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},

    {id: 61, mapId:"mapID61", name:"Cliffwall", img: regions[61], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 62, mapId:"mapID62", name:"Frozen Tundra", img: regions[62], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 63, mapId:"mapID63", name:"Glacier's Edge", img: regions[63], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 64, mapId:"mapID64", name:"Icy heights", img: regions[64], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 65, mapId:"mapID65", name:"Cold Peak", img: regions[65], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 66, mapId:"mapID66", name:"Dessert's Crossing", img: regions[66], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
    {id: 67, mapId:"mapID67", name:"Frostwood", img: regions[67], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "Blue"},
    {id: 68, mapId:"mapID68", name:"Frostwatch", img: regions[68], points_red: 0, points_blue: 0, points_yellow: 0, points_green: 0, your_points: 0, controlledBy: "No Team"},
]
